---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: pingworks/docker-ws-baseimg:0.2
      
suites:
  - name: default
    run_list:
    attributes:
