name 'ws_kitchen_docker_test'
maintainer 'Alexander Birk'
maintainer_email 'birk@pingworks.de'
license 'Apache 2.0'
description 'Installs/Configures ws_kitchen_docker_test'
long_description 'Installs/Configures ws_kitchen_docker_test'
version '0.1.1'
