name             'ws-kitchen-docker-test'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ws-kitchen-docker-test'
long_description 'Installs/Configures ws-kitchen-docker-test'
version          '0.1.0'
